vscode:
  extensions:
    - dracula-theme.theme-dracula@2.20.0:3ytFGkwBUqAAYaWVrFDm3w==
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - Shan.code-settings-sync@3.4.3:lADxYq3EKc+4gqNNppMuiQ==